### ISSUE TITLE
Issue with latest beta (2.1.24)

### ISSUE THREAD

**Issue by Cupbox** [FooSoft/anki-connect#145]
Looking up something on Yomichan popup's the following error on Anki Beta 2.1.24 [changelog](https://betas.ankiweb.net/#/) 
Anki 2.1.24 (9dda5cf6) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-21 19:23:18

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\__init__.py", line 73, in advance
    self.server.advance()
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 118, in advance
    self.advanceClients()
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 133, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 133, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 62, in advance
    self.writeBuff += self.handler(req)
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 152, in handlerWrapper
    body = json.dumps(self.handler(params)).encode('utf-8')
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type RepeatedScalarFieldContainer is not JSON serializable

**Comment by zero57** [comment]
Also getting this issue after updating to `anki 2.1.24`. Falling back to `2.1.22` works fine.

**Comment by FooSoft** [comment]
Could you please add repro steps? I can see that it's failing to encode the result of some sort of action as json, but it is not clear what the action that you are trying to execute is.

**Comment by zero57** [comment]
1. Install `anki 2.1.24`
2. Install `AnkiConnect` from https://ankiweb.net/shared/info/2055492159 last updated on: 2020-04-24
3. On Windows 10, Google Chrome `Version 81.0.4044.129 (Official Build) (64-bit)`, with Yomichan version `20.4.10.1` JMdict dictionary installed, hold shift and hover over a Japanese word, such as 東京
4. Anki throws error in client: `TypeError: Object of type RepeatedScalarFieldContainer is not JSON serializable`

**Comment by zero57** [comment]
Weird, I reinstalled anki 2.1.24 and it works fine now... It was happening whenever I was holding shift and hovering over any Japanese word with Yomichan version 20.4.10.1. 

We can probably close this for now until we have reproducible steps. Thanks.

**Comment by Pintliz** [comment]
I have encountered this too. It only happens when I hover over a word that was already added

**Comment by zero57** [comment]
Confirmed.

Windows 10 64-bit
1. Install `anki 2.1.24`
2. Install `Yomichan 20.4.10.1`
3. Install `Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)`
4. Add word such as 東京 to Anki deck via Yomichan.
5. Hover over 東京 with Yomichan after adding it, and get the following error message

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-29 21:08:17

Caught exception:
Traceback (most recent call last):
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\__init__.py", line 76, in advance
    self.server.advance()
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 118, in advance
    self.advanceClients()
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 133, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 133, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 62, in advance
    self.writeBuff += self.handler(req)
  File "C:\Users\An\AppData\Roaming\Anki2\addons21\2055492159\web.py", line 152, in handlerWrapper
    body = json.dumps(self.handler(params)).encode('utf-8')
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type RepeatedScalarFieldContainer is not JSON serializable
```
