### ISSUE TITLE
Error when changing note type in guiAddCard

### ISSUE THREAD

**Issue by bnpd** [FooSoft/anki-connect#265]
When a note type is specified using AnkiConnect for guiAddCards and the end user then tries to change it using the Anki GUI, it will cause an error:

`Error
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-11 10:51:55

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "aqt/editor.py", line 534, in <lambda>
  File "aqt/modelchooser.py", line 98, in onModelChange
  File "aqt/hooks_gen.py", line 837, in __call__
TypeError: **onModelChange() takes 1 positional argument but 2 were given**
`

**Comment by enrico3** [comment]
I am also getting this error on Windows 10 with slightly different versions of Python, Qt and PyQt:

> Debuginformationen:
Anki 2.1.44 (b2b3275f) **Python 3.8.6 Qt 5.14.2 PyQt 5.14.2**
Platform: **Windows 10**
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-24 19:27:03
Caught exception:
Traceback (most recent call last):
  File "aqt\modelchooser.py", line 98, in onModelChange
  File "aqt\hooks_gen.py", line 837, in __call__
TypeError: onModelChange() takes 1 positional argument but 2 were given
