### ISSUE TITLE
error today when i just open anki

### ISSUE THREAD

**Issue by ghost** [FooSoft/anki-connect#314]
I'm sorry to bother you if this chat is not for that. But I've been looking all over the internet for a solution and haven't found it.
 
I have been using anki for years now with anki connect/yomichan. I upgraded anki to the most advanced version my mac os allows (2.1.35 via the alternative on the official site). But today when I launched anki it showed me an error message that I quote:
 
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/michel/Library/Application Support/Anki2/addons21/2055492159/__init__.py", line 21, in <module>
    raise Exception("Minimum Anki version supported: 2.1.45")
Exception: Minimum Anki version supported: 2.1.45

If I understand correctly now to have anki connect, you need to be in possession of version 2.1.45 but I can't install it. I am on an OS X el capitan v.20.11.6 from 2008 so I can't. 
Is there any way to install the old version of anki connect so I can continue to use it? Or how can I solve this?

I sincerely hope you can help me quickly. I use this tool every day to work at the university and it worked perfectly so far. 

Translated from French with www.DeepL.com 

Naomi

**Comment by Kuromarmotte** [comment]
ps: of course i already try fex times to delete the adds on "anki connect" and re-download and -upload it.

**Comment by Garbaz** [comment]
Same here. I'm using Anki 2.1.35 for other old addons that haven't been updated to newer versions.

Would be nice if at least the old version still compatible with Anki 2.1.35 were kept available. And for the information on [AnkiWeb](https://ankiweb.net/shared/info/2055492159) to be updated accordingly to prevent the newer version from being installed/updated for older versions of Anki.

**Comment by Kuromarmotte** [comment]
It makes me feel better to know that it's not me that's messed up or my computer that has a problem. Now we have to solve this.
I sent 2 emails to the developer but I'm not sure if he has that much to do or if he even sees my emails. 
It would be nice if someone could pass on the information. 
I know many of you have new computers but please think of the people who have old ones too. 
A lot of students at my college (and I think a lot of Japanese students everywhere) have cheap computers so they are older versions. I think the most supported version at the lowest is at least 2.1.26. It would be great if we could keep both the old and the new version of anki connect so everyone would be happy.

**Comment by Kuromarmotte** [comment]
Or at least tell on the page that anki connect world only on 2.1.45 version or more on anki web. It would be so helpful.

**Comment by ItsArrrow** [comment]
I upgraded to the latest Anki version 2.1.49. While Anki connect started working again, a lot of my other extensions broke. Really hope it starts working again for lower versions.

**Comment by FooSoft** [comment]
I've temporarily rolled back to the previous version, until we can figure this out. It looks like a lot more folks are using older versions than I thought. @oakkitten as an FYI.

**Comment by Kuromarmotte** [comment]
Thank for you consideration, that really nice and gentle

**Comment by Geniusssmit** [comment]
Please !

**Comment by oakkitten** [comment]
It is possible to upload different addon versions for different Anki versions! So users who are able to use the later Anki versions can use the latest version of an add-on, and those who aren't can keep using the old one.

![image](https://user-images.githubusercontent.com/1710718/165752154-88c7182e-db56-4434-924c-10d0173ba781.png)

**Comment by Kuromarmotte** [comment]
Oh I see...
But where I supossed to put this number on my anki desktop app? 
Because today I juste open anki and he immediately say me that the add-on has a problem. And on the AnkiWeb page there only one number for upload the adon.
I'm sorry, my English is very approximate 

I see what you want to say and that fantastic but I don't kwno how to prevent anki to use the newer version of Anki connect and rest on the older version.
What command should I exactly do?

Thanks in advance for your precious time

**Comment by oakkitten** [comment]
Oh, sorry, I wasn't clear. This is not a fix that the users can do, this is the form available to the one who uploads the addon to Anki Web. Then your Anki should be able to automatically download the appropriate compatible version.

**Comment by Kuromarmotte** [comment]
Oh... don't worry I must have misunderstood. 

After I don't know if it's possible or feasible because I don't know anything about programming, but why not make two versions of anki connect by smoothing the old one and making the new one available too. 
Because it must be very frustrating for you not to be able to offer your great work to users of the latest version of anki and I have absolutely nothing against progress so I understand your desire to advance your project. 

Especially since I must be one of the small dinosaurs left on our stone computers, ha ha 
so very sorry if i bother you with that ....

**Comment by FooSoft** [comment]
Yeah that sounds good, I'll upload with proper version gating this weekend.
