### ISSUE TITLE
Error when starting Anki

### ISSUE THREAD

**Issue by SuzanaK** [FooSoft/anki-connect#347]
When I start Anki after installation of anki-connect, I get the following error:
```

Beim Laden von 'AnkiConnect':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/privat/.local/share/Anki2/addons21/2055492159/__init__.py", line 57, in <module>
    class AnkiConnect:
  File "/home/privat/.local/share/Anki2/addons21/2055492159/__init__.py", line 58, in AnkiConnect
    _anki21_version = int(aqt.appVersion.split('.')[-1])
ValueError: invalid literal for int() with base 10: '0beta36'
```

I cannot open localhost:8765.

My Anki version is 2.1.0beta36, so it is really a String that cannot be parsed to an integer.  
I have Linux Mint 19 and the python3 version is 3.6.9

**Comment by SuzanaK** [comment]
Nevermind, you can close this issue. I thought I had installed the version from the website but actually I had already installed the buggy beta version from the Ubuntu repositories. I uninstalled it and installed it again and now I have 2.1.49. So the error cannot occur anymore. 

Unfortunately, now Anki freezes on startup which is a known bug for this version, and I can't install the newer version because of an outdated gclib version. So no Anki for me until I find the time to upgrade the operating system.
