### ISSUE TITLE
Socket already in use, cannot connect

### ISSUE THREAD

**Issue by felixvd** [FooSoft/anki-connect#89]
After installing the add-on on Mac, Anki starts up to the following error:

```
Traceback (most recent call last):
  File "/Users/felix/Library/Application Support/Anki2/addons/yomi_base/anki_connect.py", line 41, in advance
    self.server.listen()
  File "/Users/felix/Library/Application Support/Anki2/addons/yomi_base/ajax.py", line 132, in listen
    self.sock.bind((address, port))
  File "socket.pyc", line 228, in meth
socket.error: [Errno 48] Address already in use
```

After initially showing other errors when activating the connection in the Chrome browser extension, it eventually does work (the data gets sent to Anki), but the error on startup remains.

It's lovely work through and through by the way. Congratulations.

**Comment by FooSoft** [comment]
Hey, so it looks like you are already running something on that socket (8765)? Can you try opening the `anki_connect.py` file and changing the port to another value?

**Comment by felixvd** [comment]
That fixes the error being displayed, but checking/unchecking the "Enable AnkiIntegration" checkbox in the Chrome extension gives the error `Extension and plugin versions incompatible`.
